apiVersion: apps/v1
kind: Deployment
metadata:
  name: han-bank-api-deployment
  labels:
    app: han-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: han-bank-api
  template:
    metadata:
      labels:
        app: han-bank-api
    spec:
      containers:
      - name: han-bank-api
        image: 843842551818.dkr.ecr.us-east-2.amazonaws.com/hanbank:7ddb3078b1feeb7a25375346250f7bb781c139b7
        ports:
        - containerPort: 8080